/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.BookieView;

import ObserverPattern.Observer;
import ObserverPattern.Subject;
import refactoring.BetESSAPI;
import model.Evento;
import model.Resultado;

/**
 *
 * @author xavier
 */
public class EndEventView extends javax.swing.JFrame implements Subject {
    
    private Observer controller;


    /**
     * Creates new form EndEventFrame
     */
    public EndEventView() {
        initComponents();
    }
    public EndEventView(Observer controller) {
        initComponents();
        this.controller = controller;
        this.jRadioButtonVitoria.setSelected(rootPaneCheckingEnabled);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonVitoria = new javax.swing.JRadioButton();
        jLabelID = new javax.swing.JLabel();
        jRadioButtonEmpate = new javax.swing.JRadioButton();
        jRadioButtonDerrota = new javax.swing.JRadioButton();
        jToggleButtonOK = new javax.swing.JToggleButton();
        jToggleButtonCancel = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButtonVitoria.setText("vitória");
        jRadioButtonVitoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonVitoriaActionPerformed(evt);
            }
        });

        jLabelID.setText("resultado do evento");

        jRadioButtonEmpate.setText("empate");
        jRadioButtonEmpate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmpateActionPerformed(evt);
            }
        });

        jRadioButtonDerrota.setText("derrota");
        jRadioButtonDerrota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDerrotaActionPerformed(evt);
            }
        });

        jToggleButtonOK.setText("ok");
        jToggleButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonOKActionPerformed(evt);
            }
        });

        jToggleButtonCancel.setText("cancel");
        jToggleButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelID)
                            .addComponent(jRadioButtonEmpate)
                            .addComponent(jRadioButtonVitoria)
                            .addComponent(jRadioButtonDerrota)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jToggleButtonOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelID)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonVitoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonEmpate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonDerrota)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonOK)
                    .addComponent(jToggleButtonCancel))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jToggleButtonCancelActionPerformed

    private void jRadioButtonVitoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonVitoriaActionPerformed
        this.jRadioButtonDerrota.setSelected(false);
        this.jRadioButtonEmpate.setSelected(false);
    }//GEN-LAST:event_jRadioButtonVitoriaActionPerformed

    private void jRadioButtonEmpateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmpateActionPerformed
        this.jRadioButtonVitoria.setSelected(false);
        this.jRadioButtonDerrota.setSelected(false);
    }//GEN-LAST:event_jRadioButtonEmpateActionPerformed

    private void jRadioButtonDerrotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDerrotaActionPerformed
        this.jRadioButtonVitoria.setSelected(false);
        this.jRadioButtonEmpate.setSelected(false);
    }//GEN-LAST:event_jRadioButtonDerrotaActionPerformed

    private void jToggleButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonOKActionPerformed
        this.notify(null, null);
    }//GEN-LAST:event_jToggleButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndEventView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndEventView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelID;
    private javax.swing.JRadioButton jRadioButtonDerrota;
    private javax.swing.JRadioButton jRadioButtonEmpate;
    private javax.swing.JRadioButton jRadioButtonVitoria;
    private javax.swing.JToggleButton jToggleButtonCancel;
    private javax.swing.JToggleButton jToggleButtonOK;
    // End of variables declaration//GEN-END:variables

    @Override
    public void notify(String channel, String message) {
        this.controller.updateObserver(message);
    }

    @Override
    public void addObserver(String channel, Observer o) {
        this.controller = o;
    }
    
    public boolean getVitoria(){
        return this.jRadioButtonVitoria.isSelected();
    }
    public boolean getEmpate(){
        return this.jRadioButtonEmpate.isSelected();
    }
    public boolean getDerrota(){
        return this.jRadioButtonDerrota.isSelected();
    }
}
