/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BetESSAPI;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.Bookie;
import model.Evento;
import model.Observer;

/**
 *
 * @author xavier
 */
public class BookieUI extends javax.swing.JFrame implements Observer {
    
    private BetESSAPI controller;
    private Bookie me;

    /**
     * Creates new form BookieUI
     */
    public BookieUI() {
        initComponents();
    }
    public BookieUI(BetESSAPI controller, Bookie bookie) {
        initComponents();
        this.controller = controller;
        this.me = bookie;
        this.jLabelNome.setText(this.me.getNome());
        this.jLabelEmail.setText(this.me.getEmail());
        this.controller.addObserverUI(this);
        this.controller.registaEvento("braga","bcl");
        //this.updateView();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEventos = new javax.swing.JTable();
        jToggleButtonNew = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNome.setText("jLabel1");

        jLabelEmail.setText("jLabel1");

        jTableEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "equipa 1", "equipa 2", "data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEventos);

        jToggleButtonNew.setText("new");
        jToggleButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonNewActionPerformed(evt);
            }
        });

        jToggleButton2.setText("update");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonNew)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButtonNew)
                        .addComponent(jToggleButton2)
                        .addComponent(jToggleButton1)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonNewActionPerformed
        NewEventForm novoEventoUI = new NewEventForm(this.controller);
        novoEventoUI.setVisible(true);
    }//GEN-LAST:event_jToggleButtonNewActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        if(this.jTableEventos.getSelectedRow()>-1){
            System.out.println("linha: "+this.jTableEventos.getSelectedRow());
            Evento e = this.controller.getEventos().get(this.jTableEventos.getSelectedRow());
            UpdateFrame updateframe = new UpdateFrame(this.controller,e);
            updateframe.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookieUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEventos;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButtonNew;
    // End of variables declaration//GEN-END:variables


    public void updateView() {
        Vector<Evento> eventos;
        try{
            eventos = this.controller.getEventos();
            DefaultTableModel model = new DefaultTableModel(new String[]{"id","equipa 1","equipa 2","data"}, 0);
            this.jTableEventos.setModel(model);
            this.jTableEventos.setCellSelectionEnabled(false);
            for(int i=0;i<eventos.size();i++)
            {
                Evento e = eventos.get(i);
                model.addRow(new String[]{new Integer(e.getId()).toString(),e.getEquipa1(),e.getEquipa2(),e.getDataEvento().toString()});
                model.fireTableDataChanged();
            }
            
        } catch (Exception ex) {
            //new ErrorWindow("Inventário", ex.getMessage(), "error", new JFrame()).wshow();
        }
    }

    @Override
    public void update(String notificacao) {
        Vector<Evento> eventos;
        try{
            eventos = this.controller.getEventos();
            DefaultTableModel model = new DefaultTableModel(new String[]{"id","equipa 1","equipa 2","data"}, 0);
            this.jTableEventos.setModel(model);
            this.jTableEventos.setCellSelectionEnabled(false);
            for(int i=0;i<eventos.size();i++)
            {
                Evento e = eventos.get(i);
                model.addRow(new String[]{new Integer(e.getId()).toString(),e.getEquipa1(),e.getEquipa2(),e.getDataEvento().toString()});
                model.fireTableDataChanged();
            }
            
        } catch (Exception ex) {
            //new ErrorWindow("Inventário", ex.getMessage(), "error", new JFrame()).wshow();
        }
    }
}

