/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BetESSAPI;
import java.util.Date;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.Bookie;
import model.Evento;
import model.Observer;
import model.Resultado;

/**
 *
 * @author xavier
 */
public class BookieUI extends javax.swing.JFrame implements View {
    
    private BetESSAPI controller;
    private Bookie me;

    /**
     * Creates new form BookieUI
     */
    public BookieUI() {
        initComponents();
    }
    public BookieUI(BetESSAPI controller, Bookie bookie) {
        initComponents();
        this.controller = controller;
        this.me = bookie;
        me.addController(controller);
        this.jLabelNome.setText(this.me.getNome());
        this.jLabelEmail.setText(this.me.getEmail());
        this.controller.addObserverUI(this);
        this.controller.registaEvento("braga","bcl");
        this.controller.registaEvento("braga","bcl");
        this.controller.registaEvento("braga","bcl");
        this.updateView(null);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEventos = new javax.swing.JTable();
        jToggleButtonNew = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButtonEnd = new javax.swing.JToggleButton();
        jToggleButtonDelete = new javax.swing.JToggleButton();
        jToggleButtonObserve = new javax.swing.JToggleButton();
        exitBT = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNome.setText("jLabel1");

        jLabelEmail.setText("jLabel1");

        jTableEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "equipa 1", "equipa 2", "data"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEventos);

        jToggleButtonNew.setText("new");
        jToggleButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonNewActionPerformed(evt);
            }
        });

        jToggleButton2.setText("update");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButtonEnd.setText("end");
        jToggleButtonEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEndActionPerformed(evt);
            }
        });

        jToggleButtonDelete.setText("delete");
        jToggleButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonDeleteActionPerformed(evt);
            }
        });

        jToggleButtonObserve.setText("observe");
        jToggleButtonObserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonObserveActionPerformed(evt);
            }
        });

        exitBT.setText("exit");
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonObserve)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButtonNew)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitBT)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButtonNew)
                        .addComponent(jToggleButton2)
                        .addComponent(jToggleButtonEnd)
                        .addComponent(jToggleButtonDelete)
                        .addComponent(jToggleButtonObserve)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(exitBT)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonNewActionPerformed
        NewEventForm novoEventoUI = new NewEventForm(this.controller);
        novoEventoUI.setVisible(true);
    }//GEN-LAST:event_jToggleButtonNewActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if(this.jTableEventos.getSelectedRow()>-1){
            Evento e = this.controller.getEventos().get(this.jTableEventos.getSelectedRow());
            UpdateFrame updateframe = new UpdateFrame(this.controller,e);
            updateframe.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButtonEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEndActionPerformed
        if(this.jTableEventos.getSelectedRow()>-1){
            Evento e = this.controller.getEventos().get(this.jTableEventos.getSelectedRow());
            EndEventFrame endframe = new EndEventFrame(this.controller, e);
            endframe.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jToggleButtonEndActionPerformed

    private void jToggleButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonDeleteActionPerformed
        if(this.jTableEventos.getSelectedRow()>-1){
            Evento e = this.controller.getEventos().get(this.jTableEventos.getSelectedRow());
            DeleteFrame deleteframe = new DeleteFrame(this.controller, e);
            deleteframe.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jToggleButtonDeleteActionPerformed

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        this.dispose();
        System.exit(WIDTH);
    }//GEN-LAST:event_exitBTActionPerformed

    private void jToggleButtonObserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonObserveActionPerformed
        if(this.jTableEventos.getSelectedRow()>-1){
            Evento e = this.controller.getEventos().get(this.jTableEventos.getSelectedRow());
            this.controller.observarEvento(e, me);
            NotificationFrame n = new NotificationFrame("Está agora a observar o evento "+e.getId()+"!");
            n.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jToggleButtonObserveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookieUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookieUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton exitBT;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEventos;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButtonDelete;
    private javax.swing.JToggleButton jToggleButtonEnd;
    private javax.swing.JToggleButton jToggleButtonNew;
    private javax.swing.JToggleButton jToggleButtonObserve;
    // End of variables declaration//GEN-END:variables


    public void updateView(String message) {
        Vector<Evento> eventos;
        if(message!=null){
            System.out.println("mensagem: "+message);
            NotificationFrame nf = new NotificationFrame(message);
            nf.setVisible(rootPaneCheckingEnabled);
        }
        else
            try{
                eventos = this.controller.getEventos();
                DefaultTableModel model = new DefaultTableModel(new String[]{"id","equipa 1","equipa 2","data","estado","resultado"}, 0);
                this.jTableEventos.setModel(model);
                this.jTableEventos.setCellSelectionEnabled(false);
                for(int i=0;i<eventos.size();i++)
                {
                    String s;

                    Evento e = eventos.get(i);                
                    model.addRow(new String[]{new Integer(e.getId()).toString(),e.getEquipa1(),
                        e.getEquipa2(),e.getDataEvento().toString(),
                        (e.getEstado()) ? "aberto" : "fechado",(e.getResultado()!=null) ? e.getResultado().toString() : ""});
                    model.fireTableDataChanged();
                }

            } catch (Exception ex) {
                //new ErrorWindow("Inventário", ex.getMessage(), "error", new JFrame()).wshow();
            }
    }

    private String setResult(Resultado r){
            if(r == Resultado.VITORIA)
                return "vitoria";
            if(r == Resultado.DERROTA)
                return "empate";
            return "derrota";		
    }
   
}

